image: go1.2
env:
  - GOPATH=/var/cache/drone
script:
  - go build
  - go test -cover -v
notify:
  email:
    recipients:
      - yoshida.keiji.84@gmail.com
      - yoshida.keiji@economica.co.jp
  hipchat:
    room: dronetest
    token: 7af96e16fbdd355c61e1a8d01344f5
