language: go
go:
- 1.2
- tip
install:
- go get code.google.com/p/go.tools/cmd/cover
script:
- go test -cover -v
env:
  global:
  - secure: J9ROQ45TGiF/BS7XpG+1TfSgFlL4NgF+3otJFtHeWdWZko689dnHrCl7WbWu30PmuQ8AtcyDtpPXlh7Sz2cS3whwsB6cwlE1yzW9xp2yp88QjqKtMiiUKREyli2SOdnrRIeV8PXd+7lQo1HSiY0ZOjrqnKcFot1V7gAXqw6l2ZI=
